dist: trusty
sudo: required
language: bash
env:
- tf_version=0.12.8
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms: 
      secure: Cny2JkJIq41dvJZxbsvBn5N+fnFFKRQj2qHP6yKRhfPpKqzSDIyujGsZFfd2o/c5YOUK0hwLK2tOM+g/RSeZogfjb5YWk28x0MhN09stj3GtKhWX6XDYdXkuRJVaCa/7IuDqxUvNxpCjGPRCShwghs9dHSHhs/Xq9or51q1J6mIAB8UvCsI7vkgsqnhTFrCsqSbwSz98zpq+l7lml6BJi6/YDsT7VAv/horNY/gllFk7Rfc402CeKGNRqVjzDY05ZcqXekbeOhPwOGi7X4Nh3etXhl1l5d6KL8bkD7COqueWhc2EiEZHzQ6KyGGTQ9NEzP8Xn10rrBZ7J40Rd3TKq2EzP1cRw6g/zGwXKMGlZGcb/XzSJRyEWTohJtZ7pBNGVBYfHwBhDczF7suKa+yT93lA5h/ubXBXzrFRPniE1sq01EFdX5Mh9BGrtV92dqtcCTckq3MgNKX0MXFBLqWcAPGVaNJELB+o5oK48AvOMXpfcntbw/kH48EgqgzSONCGQseGXKpgolb/1HK+DeibqdLc/w44Z/UBdzKIwi6yJ4yMEa1i+7z0XW+5Z8A9qhOuesNI6lC2Kd8DTw7lQhVcma+IvRt/bIZ1kWCjbA+gaxL5QMJxfaiaS07RRy6s0O9diQgarITh80QIDYJdHaHUPSOahtcuji4an29mlkJKt4I=
