dist: trusty
sudo: required
language: bash
env:
- tf_version=0.12.8
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: nZ7tIxzRLAdJs9bgVZzX0PC91Q+kHSOW+W9iTbDz0gcm6S2XeYHhPjRUwPkwrII0+o/otUv3Hf7UHxtv4+p5xPj06vqHUXBB0f64lbXEqFnKs7L/JM4Hm3coDFGu+P8Q/jzYTtMS78H9wZ1qXGNwM4k87eg7iRS+qG/38P0BmvdVzstT35gItJkB+B/3pLthGn0dk8iRKVklnAOPYHIIF8qPF2GryzfPk2X8jOxRnwcHL+Uxbfoh2T06weJAaQ2uEsFQwsyHT3Im4MQvke1BI5NRBfwuEPXTKHo1GA3xIExlTG3jqtRH6NB5jfgj7jrg/H8b0TebH+/Rv2oBasgdvpdp7mnNbpSI9Ds8qLGhceQXQgbJ8DyzJb44/rtNowIFmH0hGqC42ZtVpLt/qAiih3ZVvFKpPplMlLa72USC8qOf7+vKbBaD6iQqvz09i96za5R/N7cceaXyVNKRVxuo+QzI1B8EGvKCxMY7pR3/sZLm++QlqKSZgawXQmBb9BmYkkrfvnHKYa8pmLDOG25SFGKj48WbO1HLu2RNl4AuMahXPU9c/2eF8kZGaleFByLkYbwRAxfjd1a2j/9RLMD7EUb80re8x+lPA/6PicX9mgsfxT4fbJurjyEHSUsmp1L5DwATEntdMZe0QzhHWNGksMxTkYsg0yF43DmYGEd55wg=
