dist: trusty
sudo: required
language: bash
env:
- tf_version=0.12.8
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: "WoZyo00pAyayXqBwKYQ8M/RLhP/M7kc7nkRE/IC0JfOQ+/0Q1A5dBo+g7NbAeB4o0BKmk7EY9Sfj/VW5uU4E3+oYFwBHS7OFlaUwNofya+24j44VgPT01cwa8DQPBTVBcbtSFEbn0Eqxda/BC5lIQs9Ajsg4NA6L4x2xNYumx5z4OrF34/+TtHzlxzpo7hbd3CFHsbovgzyU0V/h3WtEkEgAlw9UJC0yaXODpZMAuuRz/kLdQB9K9R2QEaUXZ8dXSdsCJ1EtnhvUZBiEhEe/4cZA3Mx9Tv+/zqsKVVMcnnDBNHGRmh1QvBu2E76ZLUAJYWSOxh8u+I3tf7EhouxERtuKRsDlXpvyElhcwnaoE+eGtnytIBqV6E1u6s/mEGSMGniSCbk8DxZNBSdHLiT5ZBIbHcyp7qR+IvtWV0IRcrhlkSuYQGBKCQoVrhhbW/PaGcJLS6GYny5VAGR4hQmiZnjld13xyzbW4/236jnlWJmW4uPsCfkcgDoGN2Y7NzIKIswbHskTb26aecK9uVR5/3mWPWPmqDbnMPpJKJHvx4mDs0dOryVv3VPc52h460cXMQJxpL+Ne+Y3hB6yULHX1w4WiCu3LFilZ61/fomPDDENlSaeZGXIfOCXx/rEtqanbpNAPEXA3QJXj5vzhFOzaL8eGlMj7sN/llMYpL51bOk="
