dist: trusty
sudo: required
language: bash
env:
- tf_version=0.12.8
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash

notifications:
  slack:
    rooms:
      secure: "HkeuQ1CoCiyK0kC64ouHlsPTUBUe5YovFPnMZmPD0fTumLk8Kp+JZl03BjU+AZ7EBnld5cvZaQucCLjPEGfIJYJHaOAxndvMK1IEPQPxFgscNoy0YekeF884+C7JT1qmwlELGBr57+5Wtl42dhxl/1iazD9dHSfd9Ee5/uUq2M/vwdGr4wtb62CnAVB1opeUQnG7xQvCTEXTMnI6KE8mER5Mvb2FbZNfWyfb4YL+OqCeunONXPtmlEEffCs84zzcXB8mZ7bD62Hmvq6nxn3QJK0QWGLQ9XtMuiZ/v+rsUmIXOlFHFnpQACW2u8J6bCW//ONIHsJqdacxSX/98VJcMgprjX0w08L91uUryqet6Ch+C2hNQytoeys3CzsSOURAz5z9rREng/7R/B+06yFfx0dtFf0p0ZUqTON37+GWul84E+SxW9OW2L18BsrpJnIjOG+x+KtPprHV5TmroAsDqBNTNEi1u7BHKdc7baS7oFhPBUbzvtUrq+3IfDJEzKZ0/V7ZGRthyVp2Y3G3KuFp13nN1Rw+zyMzPJ1CFc2J2xK+UCvGLhHhyIfGHDkvpCeKEDI2H9i6DaP2HER/YFUE6/psIj32uAR+RgCXMZB8UDWTumW2lgFhO6dsrC0D+ln0uiEMVpQm03lUuj4Hr8PINDg1izaliE6Ynbr2PQ22uWo="
