FROM ubuntu:16.04

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends build-essential ruby-full ruby-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists* && \
    gem install bundler --no-ri --no-rdoc

ENV APP_HOME /app
COPY Gemfile* $APP_HOME/
WORKDIR $APP_HOME
RUN bundle install
COPY . $APP_HOME/

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
