global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#pavel_pavlov'
