version: '3.3'

services:
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - back_net

  alertmanager:
    image: ${USERNAME}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net

  mongodb-exporter:
    image: ppavlov39/mongodb-exporter
    environment:
      - MONGODB_URI='mongodb://post_db:27017'
    networks:
      - back_net

  blackbox-exporter:
    image: ppavlov39/blackbox-exporter
    ports:
      - '9115:9115'
    user: root
    command:
      - '--config.file=/config/blackbox.yml'
    networks:
      - front_net
      - back_net

  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/root.fs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - back_net

  grafana:
    image: grafana/grafana:5.0.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin!123?
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - back_net

volumes:
  prometheus_data:
  grafana_data:

networks:
  front_net:
    driver: bridge
  back_net:
    driver: bridge
