version: '3'
services:

  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - logging_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - logging_net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    ports:
      - "5601:5601"
    networks:
      - logging_net

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - back_net
      - front_net

networks:
  logging_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.52.0.0/24
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/24
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.51.0.0/24
