version: '3.3'

services:
  post_db:
    image: mongo:${MONGO_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${USERNAME}/ui:${REDDIT_UI_VERSION}
    ports:
      - ${REDDIT_HOST_PORT}:${REDDIT_CT_PORT}/tcp
    networks:
      - front_net
    depends_on:
      - post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USERNAME}/post:${REDDIT_POST_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - front_net
      - back_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: ${USERNAME}/comment:${REDDIT_COMMENT_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/24
  back_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.51.0.0/24
