apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gitlab-gitlab
    chart: gitlab-omnibus-0.1.37
    heritage: Tiller
    release: gitlab
  name: gitlab-gitlab
  selfLink: /api/v1/namespaces/default/services/gitlab-gitlab
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: ssh
  - name: mattermost
    port: 8065
    protocol: TCP
    targetPort: mattermost
  - name: registry
    port: 8105
    protocol: TCP
    targetPort: registry
  - name: workhorse
    port: 8005
    protocol: TCP
    targetPort: workhorse
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: prometheus
  - name: web
    port: 80
    protocol: TCP
    targetPort: workhorse
  selector:
    name: gitlab-gitlab
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
